<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // interface
    'Choose from list'              => 'Выберите из списка',
    'Will be generated'             => 'Будет сгенерировано',
    // actions
    'Select file...'                => ' Выберите файл...',    // space required
    'Submit'                        => 'Отправить',
    'Activate'                      => 'Подключить',
    'Add'                           => 'Добавить',
    'Create'                        => 'Создать',
    'Update'                        => 'Обновить',
    'Edit'                          => 'Редактировать',
    'Save'                          => 'Сохранить',
    'Delete'                        => 'Удалить',
    'Deactivate'                    => 'Отключить',
    'Overview'                      => 'Обзор',
    'Search'                        => 'Поиск',
    'Import'                        => 'Загрузить',
    'Export'                        => 'Выгрузить',
    'Migrate'                       => 'Перенести',
    'Back'                          => 'Назад',
    'Go back'                       => 'Вернуться',
    // questions
    'Are you sure?'                 => 'Вы уверены?',
    // data
    'ID'                            => 'ID',
    'Version'                       => 'Версия',
    'Url'                           => 'Адрес ресурса',
    'Page'                          => 'Страница',
    'Route'                         => 'Локальный адрес',
    'Name'                          => 'Название',
    'Type'                          => 'Тип',
    'Title'                         => 'Заголовок',
    'Slug'                          => 'Пай',
    'Description'                   => 'Описание',
    'Params'                        => 'Параметры',
    'Value'                         => 'Значение',
    'Content'                       => 'Содержимое',
    'Message text'                  => 'Текст сообщения',
    'Preview'                       => 'Превью',
    'Status'                        => 'Статус',
    'Active'                        => 'Статус активности',
    'Category'                      => 'Категория',
    'Created By'                    => 'Автор',
    'Updated By'                    => 'Отредактировано',
    'Created At'                    => 'Дата создания',
    'Updated At'                    => 'Дата обновления',
    'Activity At'                   => 'Последняя активность',
    'Edited At'                     => 'Дата редактирования',
    'Updated'                       => 'Обновлен',
    'Last update'                   => 'Последнее обновление',
    'Uploaded At'                   => 'Дата загрузки',
    'Position'                      => 'Позиция',
    'Release date'                  => 'Дата релиза',
    'Access control'                => 'Контроль доступа',
    'Access permission'             => 'Привилегия доступа',
    'Children records'              => 'Дочерние записи',
    // types
    'list'                          => 'список',
    'string'                        => 'текст',
    'number'                        => 'число',
    'boolean'                       => 'да/нет',
    'date'                          => 'дата',
    // date & time
    'Today'                         => 'Сегодня',
    'Edited by {username} ({date})' => 'Отредактировал(а) {username} ({date})',
];
