<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Internal error'                                                             => 'Внутренняя ошибка сервера',
    'Engine error'                                                               => 'Внутренняя ошибка движка',
    'Please contact us if you think this is a server error: {0}. Thank you.'     => 'Информация по данной ошибке уже отправлена нам. Если Вы хотите ускорить процесс ее рассмотрения, можете написать нам: {0}.',
    'The above error occurred while the Web server was processing your request.' => 'Данная ошибка возникла на стороне сервера при обработке Вашего запроса',
    'Invalid value for type "{0}"'                                               => 'Некорректное значение для типа "{0}"',
    'Invalid file path "{0}"'                                                    => 'Некорректный путь файла "{0}"',
    "File '{file}' has invalid extension. Valid extensions: {extensions}"        => "Файл '{file}' имеет недопустимое расширение. Поддерживаемые расширения: {extensions}",
    "File '{file}' has invalid MIME type. Valid formats: {extensions}"           => "Файл '{file}' имеет недопустимый формат. Поддерживаемые форматы: {extensions}",
    'Invalid config file "{0}"'                                                  => 'Некорректный файл конфигурации "{0}"',
    "Config param '{0}' must be defined"                                         => "Параметр '{0}' должен присутствовать в файле конфигурации",
    "Value '{0}' of config param '{1}' is restricted"                            => "Значение '{0}' параметра '{1}' файла конфигурации является недопустимым",
    "Value '{0}' of config param '{1}' has invalid format"                       => "Значение '{0}' параметра '{1}' файла конфигурации является недопустимым",
    "Service '{0}' should be activated to perform this action"                   => "Для совершения данного действия необходимо подключить услугу '{0}'",
    'Incorrect route value'                                                      => 'Некорректное значение локального адреса',
    'Route "{0}" already has been taken'                                         => 'Локальный адрес "{0}" уже используется',
];
