#!/usr/bin/env php
<?php

defined('YII_APP_CONSOLE') or define('YII_APP_CONSOLE', true);
defined('YII_APP_WEB') or define('YII_APP_WEB', false);
defined('YII_APP_PATH_CONFIG') or define('YII_APP_PATH_CONFIG', __DIR__ . DIRECTORY_SEPARATOR . 'config');

// dev
if (file_exists(YII_APP_PATH_CONFIG . DIRECTORY_SEPARATOR . 'ENV_DEV')) {
    defined('YII_ENV') or define('YII_ENV', 'dev');
}
// test
elseif (file_exists(YII_APP_PATH_CONFIG . DIRECTORY_SEPARATOR . 'ENV_TEST')) {
    defined('YII_ENV') or define('YII_ENV', 'test');
}
// prod
else {
    defined('YII_ENV') or define('YII_ENV', 'prod');
}

$config = array_replace_recursive(
    require(YII_APP_PATH_CONFIG . implode(DIRECTORY_SEPARATOR, ['', 'default', 'console.php'])),
    require(YII_APP_PATH_CONFIG . implode(DIRECTORY_SEPARATOR, ['', YII_ENV, 'console.php']))
);

require($config['vendorPath'] . DIRECTORY_SEPARATOR . 'autoload.php');
require($config['vendorPath'] . implode(DIRECTORY_SEPARATOR, ['', 'yiisoft', 'yii2', 'Yii.php']));

Yii::setAlias('@tests', __DIR__ . DIRECTORY_SEPARATOR . 'tests');

exit((new yii\console\Application($config))->run());
