<?php

/**
 * Author: Pavel Petrov <itnelo@gmail.com>
 * Date: 13.03.16 7:34
 */

namespace site\modules\design\interfaces;

interface ContextInterface
{
    /**
     * Performs statements execution for initialization purposes
     * This method should be called right before rendering stage
     * and performs setting up theme pathMap, ensuring $view extension
     *
     * @param string $view
     * @return string View file path with explicit extension (see design module params, "view_extension")
     */
    public function configure($view);

    /**
     * Returns indexed array of placeholders names which will be rendered as additional params
     * This params should be merged with original $params generated by controller action
     * Method will be called during rendering stage
     *
     * @param string $view
     * @return array
     */
    public function getGlobalPlaceholders($view);
}
